listen_addresses = ''
unix_socket_directories = '/run/postgresql'
max_connections = 50

shared_buffers = 64MB
effective_cache_size = 128MB
work_mem = 4MB
maintenance_work_mem = 32MB

wal_level = replica
max_wal_size = 256MB
min_wal_size = 64MB
checkpoint_completion_target = 0.9

random_page_cost = 1.1
effective_io_concurrency = 200

log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 1000
log_line_prefix = '%t [%p]: '

autovacuum_max_workers = 2
autovacuum_naptime = 60s

ssl = off
